#username pode ser tamb√©m postgres
spring:
  datasource:
    url : jdbc:postgresql://localhost:5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username : postgres
    password : root

  jpa:
    show-sql : true
    hibernate:
      ddl-auto : update

    properties:
      hibernate.format_sql : true

  logging :
    level :
      org :
        hibernate :
          try : trace